server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: selfaxiom
  flyway:
    enabled: true
    default-schema: selfaxiom
    schemas: selfaxiom
